theme: jekyll-theme-minimal

title: Jay Mondal

description: I am a freelance content writer and digital marketing consultant, currently I am pursuing bachelor degree in English literature
google_analytics: <jay151061>
color: black
